name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  english_words: ^4.0.0
  xml: ^6.3.0
  provider: ^6.1.5
  supabase_flutter: ^2.9.1
  http: ^1.4.0
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  firebase_core: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/spray_wall.jpeg
