@SprayWallAPI_HostAddress = http://localhost:5278
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6IlFLQXFMSkszNWlxeDd5NTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2ZvaWxkb2dncGJ1Yml2dWlncW1qLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZGNiZjJkZS0zODBjLTQxMzctYmZjYy00ZjkwNDVkZDIyMWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU0Mjc5OTg1LCJpYXQiOjE3NTQyNzYzODUsImVtYWlsIjoid2lsbGlhbWJjYXN0bmVyQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJ3aWxsaWFtYmNhc3RuZXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiOGRjYmYyZGUtMzgwYy00MTM3LWJmY2MtNGY5MDQ1ZGQyMjFmIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTQyNzYzODV9XSwic2Vzc2lvbl9pZCI6IjcxYjk2MDQ5LTY5MmItNDgyNy1iYjA2LTZjMzExMzBmYTNiYyIsImlzX2Fub255bW91cyI6ZmFsc2V9.dbEfRcZE5xQ49Tuy5_GqOtaBao93U0XyPp2wo8VQ_U4
GET {{SprayWallAPI_HostAddress}}/climbs
Accept: application/json
Authorization: Bearer {{AccessToken}}

###
